- hosts: terraform-ansible
  tasks:
  - name: Instalando o python3 e virtualenv
    apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: yes

  - name: Instalando a virtualização (django e o djangorestframework)
    pip:
      virtualenv: /home/ubuntu/projeto/env
      name:
        - django
        - djangorestframework

  - name: Iniciando o projeto
    shell: '. /home/ubuntu/projeto/env/bin/activate; django-admin startproject setup /home/ubuntu/projeto/'

  - name: Alterando o hosts do settings
    lineinfile:
      path: /home/ubuntu/projeto/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes

  - name: Rodando o server
    shell: 'cd /home/ubuntu/projeto; . env/bin/activate; python manage.py runserver 0.0.0.0:8000'
    